export const categoryOptions = {
	movie: [
		{ id: 28, name: 'Action' },
		{ id: 12, name: 'Adventure' },
		{ id: 16, name: 'Animation' },
		{ id: 35, name: 'Comedy' },
		{ id: 80, name: 'Crime' },
		{ id: 99, name: 'Documentary' },
		{ id: 18, name: 'Drama' },
		{ id: 10751, name: 'Family' },
		{ id: 14, name: 'Fantasy' },
		{ id: 27, name: 'Horror' },
		{ id: 9648, name: 'Mystery' },
		{ id: 10749, name: 'Romance' },
		{ id: 878, name: 'Science Fiction' },
		{ id: 53, name: 'Thriller' },
	],
	series: [
		{ id: 10759, name: 'Action & Adventure' },
		{ id: 16, name: 'Animation' },
		{ id: 35, name: 'Comedy' },
		{ id: 80, name: 'Crime' },
		{ id: 99, name: 'Documentary' },
		{ id: 18, name: 'Drama' },
		{ id: 10751, name: 'Family' },
		{ id: 10762, name: 'Kids' },
		{ id: 9648, name: 'Mystery' },
		{ id: 10763, name: 'News' },
		{ id: 10764, name: 'Reality' },
		{ id: 10765, name: 'Sci-Fi & Fantasy' },
	],
}
